services:
  # Employee DB
  employee-db:
    image: mysql:8.0
    container_name: employee-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employeedb
      MYSQL_USER: empuser
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - employee_data:/var/lib/mysql
    networks:
      - backend

  # Attendance DB
  attendance-db:
    image: mysql:8.0
    container_name: attendance-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: attendancedb
      MYSQL_USER: attuser
      MYSQL_PASSWORD: admin123
    ports:
      - "3308:3306"
    volumes:
      - attendance_data:/var/lib/mysql
    networks:
      - backend

  # Employee Management Backend
  employee-management:
    image: ./EM-backend
    container_name: em-backend
    restart: unless-stopped
    depends_on:
      - employee-db
    ports:
      - "8001:8001"
    networks:
      - backend
    environment:
      - DB_HOST=employee-db
      - DB_PORT=3306
      - DB_DATABASE=employeedb
      - DB_USERNAME=empuser
      - DB_PASSWORD=admin123
    command: >
      sh -c "composer install &&
             php artisan migrate &&
             php artisan serve --host=0.0.0.0 --port=8001"

  # Attendance Backend
  attendance:
    image: ./AM-backend
    container_name: am-backend
    restart: unless-stopped
    depends_on:
      - attendance-db
      - employee-management
    ports:
      - "8002:8002"
    networks:
      - backend
    environment:
      - DB_HOST=attendance-db
      - DB_PORT=3306
      - DB_DATABASE=attendancedb
      - DB_USERNAME=attuser
      - DB_PASSWORD=admin123
      - EMPLOYEE_API_URL=http://employee-management:8001/api/employees
      - EM_USERS_API_URL=http://employee-management:8001/api/users
    command: >
      sh -c "composer install &&
             php artisan migrate &&
             php artisan serve --host=0.0.0.0 --port=8002"

  # Frontend (Next.js)
  frontend:
    build: ./frontend
    container_name: am-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - attendance
    networks:
      - frontend
    command: "npm run dev"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

  # phpMyAdmin (GUI for both MySQL databases)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - employee-db
      - attendance-db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: employee-db,attendance-db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    networks:
      - backend

volumes:
  employee_data:
  attendance_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
